language: csharp
solution: rest-web-service.sln
install:
  - nuget restore rest-web-service.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release rest-web-service.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./UnitTestProject/bin/Release/UnitTestProject.dll
